
// This file has been generated by the GUI designer. Do not modify.
namespace YahtzeeSharp
{
	public partial class frmError
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Frame frame2;

		private global::Gtk.Label label3;

		private global::Gtk.Frame frame3;

		private global::Gtk.Label label4;

		private global::Gtk.Frame frame4;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TextView txtErrorDetails;

		private global::Gtk.Frame frame5;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnCopyErrorText;

		private global::Gtk.Button btnEmail;

		private global::Gtk.Frame frame6;

		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget YahtzeeSharp.frmError
			this.Events = ((global::Gdk.EventMask)(256));
			this.Name = "YahtzeeSharp.frmError";
			this.Title = global::Mono.Unix.Catalog.GetString ("An error has occured.");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child YahtzeeSharp.frmError.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Events = ((global::Gdk.EventMask)(256));
			w1.Name = "dialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "An error has occured. I appologyze for the inconvinience.\nI would appriciate it if you would take a minute to send the \nerror to me so I can make the program better. ";
			this.frame2.Add (this.label3);
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			// Container child frame3.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.HeightRequest = 27;
			this.label4.Name = "label4";
			this.label4.LabelProp = "Error Details";
			this.frame3.Add (this.label4);
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			// Container child frame4.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.txtErrorDetails = new global::Gtk.TextView ();
			this.txtErrorDetails.HeightRequest = 124;
			this.txtErrorDetails.CanFocus = true;
			this.txtErrorDetails.Events = ((global::Gdk.EventMask)(2097152));
			this.txtErrorDetails.Name = "txtErrorDetails";
			this.txtErrorDetails.Editable = false;
			this.txtErrorDetails.WrapMode = ((global::Gtk.WrapMode)(2));
			this.txtErrorDetails.PixelsAboveLines = 4;
			this.txtErrorDetails.RightMargin = 5;
			this.scrolledwindow1.Add (this.txtErrorDetails);
			this.frame4.Add (this.scrolledwindow1);
			this.vbox2.Add (this.frame4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame4]));
			w8.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			// Container child frame5.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCopyErrorText = new global::Gtk.Button ();
			this.btnCopyErrorText.CanFocus = true;
			this.btnCopyErrorText.Name = "btnCopyErrorText";
			this.btnCopyErrorText.Label = "Copy Error";
			this.hbox1.Add (this.btnCopyErrorText);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCopyErrorText]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			w9.Padding = ((uint)(12));
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnEmail = new global::Gtk.Button ();
			this.btnEmail.CanFocus = true;
			this.btnEmail.Name = "btnEmail";
			this.btnEmail.Relief = ((global::Gtk.ReliefStyle)(2));
			this.btnEmail.Label = "yarrith.devos@student.kdg.be";
			this.hbox1.Add (this.btnEmail);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnEmail]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(28));
			this.frame5.Add (this.hbox1);
			this.vbox2.Add (this.frame5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame5]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.vbox2.Add (this.frame6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame6]));
			w13.Position = 4;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w14.Position = 0;
			// Internal child YahtzeeSharp.frmError.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Events = ((global::Gdk.EventMask)(256));
			w15.Name = "YahtzeeSharp.frmError_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child YahtzeeSharp.frmError_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanDefault = true;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("OK");
			this.AddActionWidget (this.button1, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.button1]));
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 418;
			this.DefaultHeight = 437;
			this.Show ();
			this.btnCopyErrorText.Clicked += new global::System.EventHandler (this.OnBtnCopyErrorTextClicked);
			this.btnEmail.Clicked += new global::System.EventHandler (this.OnBtnEmailClicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		}
	}
}
