
// This file has been generated by the GUI designer. Do not modify.
namespace YahtzeeSharp
{
	public partial class frmAboutHelper
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TextView txtText;

		private global::Gtk.Frame frame2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget YahtzeeSharp.frmAboutHelper
			this.WidthRequest = 600;
			this.HeightRequest = 450;
			this.Name = "YahtzeeSharp.frmAboutHelper";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmAboutHelper");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("YSlogo.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 600;
			this.DefaultHeight = 450;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child YahtzeeSharp.frmAboutHelper.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.txtText = new global::Gtk.TextView ();
			this.txtText.CanFocus = true;
			this.txtText.Name = "txtText";
			this.txtText.Editable = false;
			this.txtText.WrapMode = ((global::Gtk.WrapMode)(2));
			this.txtText.RightMargin = 3;
			this.scrolledwindow1.Add (this.txtText);
			this.vbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
			w2.Position = 0;
			w2.Padding = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame2.BorderWidth = ((uint)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.HeightRequest = 31;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = global::Mono.Unix.Catalog.GetString (" Ok ");
			this.hbuttonbox2.Add (this.btnOk);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnOk]));
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbuttonbox2]));
			w4.Position = 0;
			this.frame2.Add (this.hbox1);
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
		}
	}
}
